# Generated by Django 3.2 on 2021-05-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Диспетчера')),
                ('passport', models.BigIntegerField(verbose_name='Номер и Серия')),
                ('phone', models.BigIntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_flight', models.PositiveSmallIntegerField(verbose_name='Номер рейса')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Диспетчера')),
                ('passport', models.BigIntegerField(verbose_name='Номер и Серия')),
            ],
        ),
        migrations.CreateModel(
            name='plain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Самолет')),
            ],
        ),
        migrations.CreateModel(
            name='terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Номер терминала')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=10, verbose_name='Тип магазина')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=30, verbose_name='Тип услуги')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Пилота')),
                ('passport', models.BigIntegerField(default=0, verbose_name='Номер и Серия')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.company')),
                ('id_plain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.plain')),
            ],
        ),
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=5, verbose_name='Терминал')),
                ('cost_h', models.PositiveIntegerField(verbose_name='Почасовая стоимость')),
                ('cost_d', models.PositiveIntegerField(verbose_name='Суточная стоимость')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='depart_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.DateTimeField(verbose_name='Время вылета')),
                ('from_where', models.CharField(max_length=25, verbose_name='Город прилета')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.company')),
                ('id_dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.dispatcher')),
                ('id_plain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.plain')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='arrival_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('from_where', models.CharField(max_length=25, verbose_name='Город вылета')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.company')),
                ('id_dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.dispatcher')),
                ('id_plain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.plain')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.terminal')),
            ],
        ),
    ]
