# Generated by Django 3.2 on 2021-05-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_parking_tipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passanger',
            name='id_flight',
        ),
        migrations.AddField(
            model_name='passanger',
            name='flight_arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.arrival_schedule'),
        ),
        migrations.AddField(
            model_name='passanger',
            name='flight_depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.depart_schedule'),
        ),
    ]
