# Generated by Django 3.2 on 2021-05-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_alter_passanger_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passanger',
            name='flight_arrival',
        ),
        migrations.RemoveField(
            model_name='passanger',
            name='flight_depart',
        ),
        migrations.AddField(
            model_name='passanger',
            name='flighе_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер рейса'),
        ),
    ]
