# Generated by Django 3.2 on 2021-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_deleted_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival_schedule',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='depart_schedule',
            name='depart_time',
        ),
        migrations.AddField(
            model_name='arrival_schedule',
            name='arrivalF_time',
            field=models.DateTimeField(null=True, verbose_name='Время вылета'),
        ),
        migrations.AddField(
            model_name='arrival_schedule',
            name='arrivalT_time',
            field=models.DateTimeField(null=True, verbose_name='Время прибытия'),
        ),
        migrations.AddField(
            model_name='depart_schedule',
            name='departF_time',
            field=models.DateTimeField(null=True, verbose_name='Время вылета'),
        ),
        migrations.AddField(
            model_name='depart_schedule',
            name='departT_time',
            field=models.DateTimeField(null=True, verbose_name='Время прибытия'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='hours',
            field=models.BigIntegerField(default=0, verbose_name='Количество летных часов'),
        ),
    ]
