# Generated by Django 3.2 on 2021-05-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_auto_20210521_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival_schedule',
            name='id_pilotONE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aONE', to='pool.pilot'),
        ),
        migrations.AddField(
            model_name='arrival_schedule',
            name='id_pilotTWO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aTWO', to='pool.pilot'),
        ),
        migrations.AddField(
            model_name='depart_schedule',
            name='id_pilotONE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dONE', to='pool.pilot'),
        ),
        migrations.AddField(
            model_name='depart_schedule',
            name='id_pilotTWO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dTWO', to='pool.pilot'),
        ),
    ]
